【問題1】行列積を手計算する  
AとBの行列積を手計算で解いてください。  
計算過程もマークダウンテキストを用いて説明してください。

In [20]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print(a_ndarray)
print(b_ndarray)

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


A=  
[[-1  2  3]   
[ 4 -5  6]  
[ 7  8 -9]]
     
B=   
[[ 0  2  1]  
[ 0  2 -8]  
[ 2  9 -1]]
     
 [[-1*0 + 2*0 + 3*2 = 6,   
 -1*2 + 2*2 + 3*9 = 29,   
 -1*1 + 2*-8 + 3*-1 = -20],  
 [4*0 + -5*0 + 6*2 = 12,   
 4*2 + -5*2 + 6*9 = 52,   
 4*1 + -5*-8 + 6*-1 = 38],  
 [7*0 + 8*0 + -9*2 = -18,  
 7*2 + 8*2 + -9*9 = -51,  
 7*1 + 8*-8 + -9*-1 = -48]]
 
 answer =  
 [[6, 29, -20]  
 [12, 52, 38]  
 [-18, -51, -48]]
 
          

【問題2】NumPyの関数による計算  
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。これらを使い行列積を計算してください。  
《3種類の違い》

np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。

今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。

In [21]:
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [22]:
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [23]:
a_ndarray@b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

行列Aの(0,0)の要素 
a
0
,
0
 と行列Bの(0,0)の要素 
b
0
,
0
 を掛け合わせる
行列Aの(0,1)の要素 
a
0
,
1
 と行列Bの(1,0)の要素 
b
1
,
0
 を掛け合わせる
行列Aの(0,2)の要素 
a
0
,
2
 と行列Bの(2,0)の要素 
b
2
,
0
 を掛け合わせる
それらの値を全て足し合わせる

In [24]:
point1 = 0
for n in range(3):
    point1 += a_ndarray[0, n]*b_ndarray[n, 0]
point1

6

【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。
行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。
計算結果である 
3
×
3
 の行列Cの各要素 
c
i
,
j
 は数式で表すと次のようになります

In [25]:
def matlix_malti(a_ndarray, b_ndarray):
    a_list = a_ndarray.tolist()　#list化
    bT_list = b_ndarray.T.tolist()　 #転置　　for で計算しやすくした。

    x = np.zeros((len(a_list[0]), len(bT_list[0])))#0行列で初期値設置　
    ii = len(a_list[0])#forする回数①
    kk = len(bT_list[0])#forする回数②
    jj = len(a_list[0])#forする回数③

    for i in range(ii):#行ナンバーa_list
        for j in range(jj):#行ナンバーb_list
            for k in range(kk):#列ナンバーa,b list
                x[i][j] = x[i][j] + a_list[i][k] * bT_list[j][k]
    return x
print(matlix_malti(a_ndarray, b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [26]:
def matlix_malti(a_ndarray, b_ndarray):
    if len(a_ndarray[0]) != len(b_ndarray):
        print('一個目の行列の列の数と二個目の行列の行の数が合いません')
    
    
    a_list = a_ndarray.tolist()
    bT_list = b_ndarray.T.tolist()

    x = np.zeros((len(a_list[0]), len(bT_list[0])))
    ii = len(a_list[0])
    kk = len(bT_list[0])
    jj = len(a_list[0])

    for i in range(ii):
        for j in range(jj):
            for k in range(kk):
                x[i][j] = x[i][j] + a_list[i][k] * bT_list[j][k]
        
    return x


d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

matlix_malti(d_ndarray, e_ndarray)

一個目の行列の列の数と二個目の行列の行の数が合いません


IndexError: index 2 is out of bounds for axis 0 with size 2

【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

numpy.transpose — NumPy v1.16 Manual

numpy.ndarray.T — NumPy v1.16 Manual

In [27]:
def matlix_malti(a_ndarray, b_ndarray):
    if len(a_ndarray[0]) != len(b_ndarray):
        print('一個目の行列の列の数と二個目の行列の行の数が合いません')
    
    
    a_list = a_ndarray.tolist()
    bT_list = b_ndarray.T.tolist()

    x = np.zeros((len(a_list[0]), len(bT_list[0])))
    ii = len(a_list[0])
    kk = len(bT_list[0])
    jj = len(a_list[0])

    for i in range(ii):
        for j in range(jj):
            for k in range(kk):
                x[i][j] = x[i][j] + a_list[i][k] * bT_list[j][k]
        
    return x

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
d_ndarray_T =  np.transpose(d_ndarray)# d_ndarray'転置'しました。
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

matlix_malti(d_ndarray_T, e_ndarray)#計算可能になった。

array([[ 33., -28.],
       [-48.,  41.]])