In [2]:
import numpy as np

## 【問題1】チャンネル数を1に限定した1次元畳み込み層クラスの作成
チャンネル数を1に限定した1次元畳み込み層のクラスSimpleConv1dを作成してください。基本構造は前のSprintで作成した全結合層のFCクラスと同じになります。なお、重みの初期化に関するクラスは必要に応じて作り変えてください。Xavierの初期値などを使う点は全結合層と同様です。

## 【問題2】1次元畳み込み後の出力サイズの計算
畳み込みを行うと特徴量の数が変化します。どのように変化するかは以下の数式から求められます。パディングやストライドも含めています。この計算を行う関数を作成してください。

## 【問題3】小さな配列での1次元畳み込み層の実験
次に示す小さな配列でフォワードプロパゲーションとバックプロパゲーションが正しく行えているか確認してください。

### Forword　手計算

In [3]:
x = np.array([1,2,3,4])#入力情報
w = np.array([3, 5, 7])#フィルター
b = np.array([1])#バイアス

In [4]:
# 1スライド目
alpha1 = np.dot(x[0:3], w.T) + b
alpha1

array([35])

In [5]:
# 2スライド目
alpha2 = np.dot(x[1:4], w.T) + b
alpha2

array([50])

In [6]:
# 畳み込んだ結果
np.array([alpha1[0], alpha2[0]])

array([35, 50])

In [7]:
#わかりにくいけどこれでもできる

a_re =  np.convolve(x[::-1],w, mode='valid') +b

x[::-1]#反対にするcode

a = a_re[::-1]
a

array([35, 50])

In [8]:
#Answer of Forword
a = np.array([35, 50])

### Backward 手計算

In [9]:
# 教師データとの誤差が以下のdelta_aだった時のバックワードの計算
delta_a = np.array([10, 20])

In [10]:
# バイアス項
delta_B = delta_a[0] + delta_a[1]

# フィルター
delta_W0 = delta_a[0]*x[0] + delta_a[1]*x[1]
delta_W1 = delta_a[0]*x[1] + delta_a[1]*x[2]
delta_W2 = delta_a[0]*x[2] + delta_a[1]*x[3]

# 入力
delta_x0 = delta_a[0]*w[0]
delta_x1 = delta_a[0]*w[1] + delta_a[1]*w[0]
delta_x2 = delta_a[0]*w[2] + delta_a[1]*w[1]
delta_x3 = delta_a[1]*w[2]

print('バイアス')
print(np.array([delta_B]))
print()

print('フィルター')
delta_W = np.array([delta_W0, delta_W1, delta_W2])
print(delta_W)
print()

print('入力')
delta_x = np.array([delta_x0, delta_x1, delta_x2, delta_x3])
print(delta_x)

バイアス
[30]

フィルター
[ 50  80 110]

入力
[ 30 110 170 140]


In [11]:
# Answer of Backward
delta_b = np.array([30])
delta_w = np.array([50, 80, 110])
delta_x = np.array([30, 110, 170, 140])

In [12]:
# これでもできる

In [13]:
right = w*10

In [14]:
left = w*20

In [15]:
delta_x_hand = np.zeros([4])
delta_x_hand[0:3] += right
delta_x_hand[1:4] += left
delta_x_hand

array([ 30., 110., 170., 140.])

In [16]:
w_left = x[0:3]*10

In [17]:
w_right = x[1:4]*20

In [18]:
delta_w_hand = w_left + w_right
delta_w_hand

array([ 50,  80, 110])

## 【問題2】1次元畳み込み後の出力サイズの計算
畳み込みを行うと特徴量の数が変化します。どのように変化するかは以下の数式から求められます。パディングやストライドも含めています。この計算を行う関数を作成してください。

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <msub>
    <mi>N</mi>
    <mrow class="MJX-TeXAtom-ORD">
      <mi>o</mi>
      <mi>u</mi>
      <mi>t</mi>
    </mrow>
  </msub>
  <mo>=</mo>
  <mfrac>
    <mrow>
      <msub>
        <mi>N</mi>
        <mrow class="MJX-TeXAtom-ORD">
          <mi>i</mi>
          <mi>n</mi>
        </mrow>
      </msub>
      <mo>+</mo>
      <mn>2</mn>
      <mi>P</mi>
      <mo>&#x2212;<!-- − --></mo>
      <mi>F</mi>
    </mrow>
    <mi>S</mi>
  </mfrac>
  <mo>+</mo>
  <mn>1</mn>
  <mspace linebreak="newline" />
</math>

N
o
u
t
 : 出力のサイズ（特徴量の数）


N
i
n
 : 入力のサイズ（特徴量の数）


P
 : ある方向へのパディングの数


F
 : フィルタのサイズ


S
 : ストライドのサイズ

In [234]:
n_in = len(x)
P_size = 0
F_size = len(w)
S_size = 1
n_out = ((n_in + 2*P_size -F_size)/S_size)+1
n_out

2.0

## 【問題4】チャンネル数を限定しない1次元畳み込み層クラスの作成
チャンネル数を1に限定しない1次元畳み込み層のクラスConv1dを作成してください。


例えば以下のようなx, w, bがあった場合は、

## forward計算

In [235]:
x = np.array([[1, 2, 3, 4], [2, 3, 4, 5]]) # shape(2, 4)で、（入力チャンネル数、特徴量数）である。
w = np.ones((3, 2, 3)) # 例の簡略化のため全て1とする。(出力チャンネル数、入力チャンネル数、フィルタサイズ)である。
b = np.array([1, 2, 3]) # （出力チャンネル数）

In [236]:
a = np.array([[16, 22], [17, 23], [18, 24]]) # shape(3, 2)で、（出力チャンネル数、特徴量数）である

In [237]:
result = np.zeros([3, 2])
for i in range(3):
    for k in range(2):
        a = (x[:, k:k+3]*w[i]).sum() + b[i]
        result[i,k] = a
result

array([[16., 22.],
       [17., 23.],
       [18., 24.]])

In [238]:
x_ = np.array([[1,2,3,4],
               [2,3,4,5]])


w_ = np.array([[[1,1,2],[2,1,1]],
              [[2,1,1],[1,1,1]],
              [[1,1,1],[1,1,1]]])


b_ = np.array([1,2,3])

# フォワードの出力
out_ = np.array([[21,29],
                [18,25],
                [18,24]])

## forward関数化

In [239]:
def forword(x, w, b):
    result = np.zeros([3, 2])
    for i in range(3):
        for k in range(2):
            a = (x[:, k:k+3]*w[i]).sum() + b[i]
            result[i,k] = a
    return result

In [240]:
forword(x_, w_, b_)

array([[21., 29.],
       [18., 25.],
       [18., 24.]])

## backword計算

In [241]:
loss_ = np.array([[9,11],
                [32,35],
                [52,56]])


# バックワードの勾配
x_delta = np.array([[125,230,204,113],
                    [102,206,195,102]])


w_delta = np.array([[[31,51,71],[51,71,91]],
                    [[102,169,236],[169,236,303]],
                    [[164,272,380],[272,380,488]]])


## delta_W手計算

In [242]:
left_x = x_[:, 0:3]

In [243]:
right_x = x_[:, 1:4]

In [244]:
delta_w1 = left_x*loss_[0, 0] + right_x*loss_[0, 1]
delta_w1

array([[31, 51, 71],
       [51, 71, 91]])

In [245]:
delta_w2 = left_x*loss_[1, 0] + right_x*loss_[1, 1]
delta_w2

array([[102, 169, 236],
       [169, 236, 303]])

In [246]:
delta_w3 = left_x*loss_[2, 0] + right_x*loss_[2, 1]
delta_w3

array([[164, 272, 380],
       [272, 380, 488]])

In [247]:
w_list = [delta_w1, delta_w2, delta_w3]
w_delta_hand = np.zeros([3,2,3])
count = 0
for w_i in w_list:
    w_delta_hand[count] = w_i
    count += 1

In [248]:
w_delta_hand

array([[[ 31.,  51.,  71.],
        [ 51.,  71.,  91.]],

       [[102., 169., 236.],
        [169., 236., 303.]],

       [[164., 272., 380.],
        [272., 380., 488.]]])

## X_delta手計算

In [249]:
#わかりにくいけどこれでもできる。　
delta_x = np.zeros([2,4])

x_pre = np.dot(w_.T, loss_)
print(x_pre)
delta_x[:, 0] = x_pre[0, :, 0]
delta_x[:, 1] = x_pre[0, :, 1] + x_pre[1, :, 0]
delta_x[:, 2] = x_pre[1, :, 1] + x_pre[2, :, 0]
delta_x[:, 3] = x_pre[2, :, 1]
delta_x

[[[125 137]
  [102 113]]

 [[ 93 102]
  [ 93 102]]

 [[102 113]
  [ 93 102]]]


array([[125., 230., 204., 113.],
       [102., 206., 195., 102.]])

## これでもできる。

In [250]:
left0 = loss_[0,0]*w_[0]

In [251]:
right0 = loss_[0,1]*w_[0]

In [252]:
left1 = loss_[1,0]*w_[1]

In [253]:
right1 = loss_[1,1]*w_[1]

In [254]:
left2 = loss_[2,0]*w_[2]

In [255]:
right2 = loss_[2,1]*w_[2]

In [256]:
left_one =left0 + left1 + left2

In [257]:
right_one = right0 + right1 + right2

In [258]:
X_delta_tryal = np.zeros([2,4])
X_delta_tryal[:, 0:3] += left_one
X_delta_tryal[:, 1:4] += right_one
X_delta_tryal

array([[125., 230., 204., 113.],
       [102., 206., 195., 102.]])

## for分を使って求める。

In [259]:
loss_ = np.array([[9,11],
                [32,35],
                [52,56]])

x_ = np.array([[1,2,3,4],
               [2,3,4,5]])

w_ = np.array([[[1,1,2],[2,1,1]],
              [[2,1,1],[1,1,1]],
              [[1,1,1],[1,1,1]]])

dX = np.zeros(list(x_.shape))
dW = np.zeros(list(w_.shape))

for k in range(loss_.shape[1]):
    for i in range(loss_.shape[0]):
        dX[:, k:k+3] +=loss_[i, k]*w_[i]
        
        dW[i] += loss_[i, k]*x_[:, k:k+3]

In [260]:
dX

array([[125., 230., 204., 113.],
       [102., 206., 195., 102.]])

In [261]:
dW

array([[[ 31.,  51.,  71.],
        [ 51.,  71.,  91.]],

       [[102., 169., 236.],
        [169., 236., 303.]],

       [[164., 272., 380.],
        [272., 380., 488.]]])

## 関数化 backward

In [262]:
def backword(x, w, dA):
    dX = np.zeros(list(x_.shape))
    dW = np.zeros(list(w_.shape))
    for k in range(loss_.shape[1]):
        for i in range(loss_.shape[0]):
            dX[:, k:k+3] +=loss_[i, k]*w_[i]
            dW[i] += loss_[i, k]*x_[:, k:k+3]
            
    return dX, dW

In [263]:
backword(x_, w_, loss_)

(array([[125., 230., 204., 113.],
        [102., 206., 195., 102.]]), array([[[ 31.,  51.,  71.],
         [ 51.,  71.,  91.]],
 
        [[102., 169., 236.],
         [169., 236., 303.]],
 
        [[164., 272., 380.],
         [272., 380., 488.]]]))

### 【問題8】学習と推定
これまで使ってきたニューラルネットワークの全結合層の一部をConv1dに置き換えてMNISTを学習・推定し、Accuracyを計算してください。

In [28]:
import numpy as np
import pandas as pd

In [29]:
from keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

Using TensorFlow backend.


In [30]:
print(X_train.shape) # (60000, 28, 28)
print(X_test.shape) # (10000, 28, 28)
print(X_train[0].dtype) # uint8

(60000, 28, 28)
(10000, 28, 28)
uint8


In [31]:
X_train = X_train.reshape(-1, 784)
X_test = X_test.reshape(-1, 784)

In [32]:
X_train = X_train.astype(np.float)
X_test = X_test.astype(np.float)
X_train /= 255
X_test /= 255
print(X_train.max()) # 1.0
print(X_train.min()) # 0.0

1.0
0.0


In [33]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
y_train_one_hot = enc.fit_transform(y_train[:, np.newaxis])
y_test_one_hot = enc.transform(y_test[:, np.newaxis])
print(y_train.shape) # (60000,)
print(y_train_one_hot.shape) # (60000, 10)
print(y_train_one_hot.dtype) # float64

(60000,)
(60000, 10)
float64


In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train_one_hot, test_size=0.2)
print(X_train.shape) # (48000, 784)
print(X_val.shape) # (12000, 784)

(48000, 784)
(12000, 784)


In [36]:
from sklearn.metrics import accuracy_score

In [193]:
class GetMiniBatch():
    """
    ミニバッチを取得するイテレータ

    Parameters
    ----------
    X : 次の形のndarray, shape (n_samples, n_features)
      訓練データ
    y : 次の形のndarray, shape (n_samples, 1)
      正解値
    batch_size : int
      バッチサイズ
    seed : int
      NumPyの乱数のシード
    """
    def __init__(self, X, y, batch_size = 20, seed=0):
        self.batch_size = batch_size
        np.random.seed(seed)
        shuffle_index = np.random.permutation(np.arange(X.shape[0]))
        self._X = X[shuffle_index]
        self._y = y[shuffle_index]
        self._stop = np.ceil(X.shape[0]/self.batch_size).astype(np.int)
    def __len__(self):
        return self._stop
    def __getitem__(self,item):
        p0 = item*self.batch_size
        p1 = item*self.batch_size + self.batch_size
        return self._X[p0:p1], self._y[p0:p1]        
    def __iter__(self):
        self._counter = 0
        return self
    def __next__(self):
        if self._counter >= self._stop:
            raise StopIteration()
        p0 = self._counter*self.batch_size
        p1 = self._counter*self.batch_size + self.batch_size
        self._counter += 1
        return self._X[p0:p1], self._y[p0:p1]

In [194]:
class He:
    """
    ガウス分布によるシンプルな初期化
    Parameters
    ----------
    sigma : float
      ガウス分布の標準偏差
    """
    def __init__(self, siguma):
        self.siguma = siguma
        
    def W(self, n_nodes1, n_nodes2):
        """
        重みの初期化
        Parameters
        ----------
        n_nodes1 : int
          前の層のノード数
        n_nodes2 : int
          後の層のノード数
        Returns
        ----------
        W :
        """
        self.siguma = np.sqrt(2/n_nodes1)
        W = self.siguma*np.random.randn(n_nodes1, n_nodes2)
        return W
    def B(self, n_nodes2):
        """
        バイアスの初期化
        Parameters
        ----------
        n_nodes2 : int
          後の層のノード数
        Returns
        ----------
        B :
        """
        self.siguma = np.sqrt(2/n_nodes2)
        B = self.siguma*np.random.randn(n_nodes2)
        return B

In [195]:
class AdaGrad:
    """
    確率的勾配降下法
    Parameters
    ----------
    lr : 学習率
    """
    def __init__(self, lr):
        self.lr = lr
#         self.h_dW = 0
#         self.h_dB = 0
        
    def update(self, layer):
        """
        ある層の重みやバイアスの更新
        Parameters
        ----------
        layer : 更新前の層のインスタンス
        """
#         from (zerotuku)
#         for key in params.keys():
#             self.h[key] += grads[key] * grads[key]
#             params[key] -= self.lr * grads[key] / (np.sqrt(self.h[key]) + 1e-7)
#         print(layer.dW.shape)

        layer.ada_W += layer.dW**2
        layer.ada_B += layer.dB**2
        
        layer.W -= self.lr*layer.dW/(np.sqrt(layer.ada_W) + 1e-7)
        layer.B -= (self.lr*layer.dB/(np.sqrt(layer.ada_B) + 1e-7)).mean(0)

        return layer

In [196]:
class Relu:

    def __init__(self):
        self.mask = None
        
    def forward(self, X):
        """
        ある層の重みやバイアスの更新
        Parameters
        ----------
        layer : 更新前の層のインスタンス
        """
        self.mask = (X <= 0)
        out = X.copy()
        out[self.mask] = 0
 
        return out

    def backward(self, dout):
        dout[self.mask] = 0
        dX = dout

        return dout

In [197]:
class Softmax_with_Loss:
    
    def __init__(self,):
        self.forword_A = None
        
    def forward(self, A):
        """
        ある層の重みやバイアスの更新
        Parameters
        ----------
        layer : 更新前の層のインスタンス
        """
        self.forword_A = np.exp(A)/(np.exp(A).sum(1).reshape(-1, 1))
        return self.forword_A

    def backward(self, y):

        return self.forword_A - y

In [198]:
class FC:
    """
    ノード数n_nodes1からn_nodes2への全結合層
    Parameters
    ----------
    n_nodes1 : int
      前の層のノード数
    n_nodes2 : int
      後の層のノード数
    initializer : 初期化方法のインスタンス
    optimizer : 最適化手法のインスタンス
    """
    def __init__(self, n_nodes1, n_nodes2, initializer, optimizer):
        self.optimizer = optimizer
        # 初期化
        # initializerのメソッドを使い、self.Wとself.Bを初期化する
        self.W = initializer.W(n_nodes1, n_nodes2)
        self.B = initializer.B(n_nodes2)
        self.dB = 0
        self.dW = 0
        self.ada_W = 0
        self.ada_B = 0
        self.v_W = 0
        self.v_B = 0
        
    def forward(self, X):
        """
        フォワード
        Parameters
        ----------
        X : 次の形のndarray, shape (batch_size, n_nodes1)
            入力
        Returns
        ----------
        A : 次の形のndarray, shape (batch_size, n_nodes2)
            出力
        """
        self.forward_Z = X.copy()
        A = np.dot(X, self.W) + self.B        
        
        return A
    def backward(self, dA):
        """
        バックワード
        Parameters
        ----------
        dA : 次の形のndarray, shape (batch_size, n_nodes2)
            後ろから流れてきた勾配
        Returns
        ----------
        dZ : 次の形のndarray, shape (batch_size, n_nodes1)
            前に流す勾配
        """

        self.dB = dA
        self.dW = np.dot(self.forward_Z.T, dA)
        dZ = np.dot(dA, self.W.T)
        # 更新
        
        self.optimizer.update(self)
        
        return dZ

## コンボル用クラス

In [205]:
class Conv1d:
    
    def __init__(self, filter_col, initializer, optimizer):
        
        self.optimizer = optimizer
        self.Filter_col = filter_col
        
        # 初期化
        self.Filter = initializer.Filter(self.Filter_col)
        self.Baias = initializer.Bias()
        self.dFilter = 0
        self.dBaias = 0
        self.forward_X = 0
        self.ada_Filter = 0
        self.ada_Baias = 0

        pass
    
    def forward(self, X):

#         backwardでもX流用したい
        self.forward_X = X.copy()
        
        sample_num,  X_col = X.shape
        
#         スライドする回数
        slide_col = X_col - self.Filter_col

#         fowardで出力　する形状の初期設定（forで計算ごとに値を埋め込んでいきたい）
        out_put = np.zeros([sample_num, slide_col])

        
        for sample in range(sample_num):
            for col in range(slide_col):
#                 forwardの計算ごとに出力の行列に計算値を埋め込み
                a = (X[sample, col : col + self.Filter_col]*self.Filter).sum() + self.Baias[col]
                out_put[sample, col] = a

        return out_put
    def backward(self, dA):
        
        X = self.forward_X
        
#         バイアス保持したい最適化関数にしようする
        self.dBaias = dA
    
    #         初期設定
        dX = np.zeros(list(X.shape))
        dFilter = np.zeros(list(self.Filter.shape))
        
        dAsample, dAcol = dA.shape
        sample_num, X_col = dX.shape
        
        for sample in range(dAsample):
            for col in range(dAcol):
#                 dX計算
                dX[sample, col:col+self.Filter_col] += dA[sample, col]*self.Filter
#                 フィルタは最適化関数　で流用するので保持したい
                self.dFilter += dA[sample, col]*X[sample, col:col+self.Filter_col]
    
#     最適化　する
        self.optimizer.update(self)

        return dX

In [200]:
class Conv_He:
    """
   コンブ用He
    """
    def __init__(self,):
        pass
        
    def Filter(filter_col):
        """
        フィルターの初期化
        Parameters
        """
        siguma = np.sqrt(2/filter_col)
        filter = siguma*np.random.randn(filter_col)
        
        return filter
    
    def Bias():
        """
        バイアスの初期化
        """
        siguma = np.sqrt(2/600)
        B = siguma*np.random.randn(600)
        
        return B

In [201]:
class AdaGrad_for_conv:
    """
    確率的勾配降下法
    Parameters
    ----------
    lr : 学習率
    """
    def __init__(self, lr):
        self.lr = lr
        pass
        
    def update(self, layer):
        """
        ある層の重みやバイアスの更新
        Parameters
        ----------
        layer : 更新前の層のインスタンス
        """

        layer.ada_Filter += layer.dFilter**2
        layer.ada_Baias += layer.dBaias**2
        
        layer.Filter -= self.lr*layer.dFilter/(np.sqrt(layer.ada_Filter) + 1e-7)
        layer.Baias -= (self.lr*layer.dBaias/(np.sqrt(layer.ada_Baias) + 1e-7)).mean(0)

        return layer

In [213]:
class ScratchSimpleNeuralNetrowkClassifier_add_conv:

        def __init__(self, verbose = True, epoch = 0 , alpha = 0.01, activater = Relu,  initializer = He, optimizer = AdaGrad, filter_col = 184):
            self.verbose = verbose
            self.n_features = 784
            self.filter_col = filter_col
            
#             コンボルあとのノード数
            self.n_nodes1 = self.n_features - self.filter_col
            self.n_nodes2 = 200
            self.n_output = 10
            self.sigma = 0.01   # ガウス分布の標準偏差
            self.batch_size=10
            self.loss_box = []
            self.epoch = epoch
            self.lr = alpha
            self.activater = activater
            self.initializer = initializer
            self.optimizer = optimizer
            
            #             コンボル用に追加したクラス
            self.conv_initializer = Conv_He
            self.optimizer_conv = AdaGrad_for_conv
            
            pass

        def fit(self, X, y, X_val=None, y_val=None):

            """
            初期値
            """
            # self.sigma : ガウス分布の標準偏差
            # self.lr : 学習率
            # self.n_nodes1 : 1層目のノード数
            # self.n_nodes2 : 2層目のノード数self, filter_col, initializer, optimizer
            # self.n_output : 出力層のノード数
            
#             コンボル層
            self.FC1 = Conv1d(self.filter_col, self.conv_initializer, self.optimizer_conv(self.lr))
            self.activation1 = self.activater()
            
            self.FC2 = FC(self.n_nodes1, self.n_nodes2, self.initializer(self.sigma), self.optimizer(self.lr))
            self.activation2 = self.activater()
            self.FC3 = FC(self.n_nodes2, self.n_output, self.initializer(self.sigma), self.optimizer(self.lr))
            self.activation3 = Softmax_with_Loss()
            """Get_mini_batch"""
            get_mini_batch = GetMiniBatch(X, y, self.batch_size)

            """エポック回イテレート"""
            for i in range(self.epoch):
                for mini_X_train, mini_y_train in get_mini_batch:

                    """
                    Forword
                    """
                    A1 = self.FC1.forward(mini_X_train)
                    Z1 = self.activation1.forward(A1)
                    A2 = self.FC2.forward(Z1)
                    Z2 = self.activation2.forward(A2)
                    A3 = self.FC3.forward(Z2)
                    Z3 = self.activation3.forward(A3)
                    """
                    Backword
                    """
                    dA3 = self.activation3.backward(mini_y_train) # 交差エントロピー誤差とソフトマックスを合わせてい
                    dZ2 = self.FC3.backward(dA3)
                    dA2 = self.activation2.backward(dZ2)
                    dZ1 = self.FC2.backward(dA2)
                    dA1 = self.activation1.backward(dZ1)
                    dZ0 = self.FC1.backward(dA1) # dZ0は使用しない
                  
                """
                Forword  after optimized weight
                """
                A1 = self.FC1.forward(X)
                Z1 = self.activation1.forward(A1)
                A2 = self.FC2.forward(Z1)
                Z2 = self.activation2.forward(A2)
                A3 = self.FC3.forward(Z2)
                Z3 = self.activation3.forward(A3)

                """
                Evaluation
                """
                print('__{}TIMES　of epoch__'.format(i+1))
                print('L0SS={}'.format(self.cross_entropy_loss(Z3, y)))
                print('ACCURACY_SCORE={}'.format(accuracy_score(y.argmax(1), Z3.argmax(1))))
                
                self.loss_box.append(self.cross_entropy_loss(Z3, y))

            if self.verbose:
                print()
                #verboseをTrueにした際は学習過程などを出力する
            return self.loss_box

        def cross_entropy_loss(self, final_Z, y):
            l =  -y*(np.log(final_Z))/self.batch_size
            L = l.sum()
            return L

        def predict(self, X):
            """
            Forword action after optimized weight
            """
            A1 = self.FC1.forward(X)
            Z1 = self.activation1.forward(A1)
            A2 = self.FC2.forward(Z1)
            Z2 = self.activation2.forward(A2)
            A3 = self.FC3.forward(Z2)
            Z3 = self.activation3.forward(A3)

            return Z3.argmax(1)

In [214]:
nn_conv1 = ScratchSimpleNeuralNetrowkClassifier_add_conv(epoch = 3 , alpha = 0.01, activater = Relu,  initializer = He, optimizer = AdaGrad, filter_col = 184)

In [215]:
%%timeit -r １ -n 1

loss_box_Tanh = nn_conv1.fit(X_train[:4000], y_train[:4000])

y_pred = nn_conv1.predict(X_val)

print(accuracy_score(y_val.argmax(1), y_pred))

__1TIMES　of epoch__
L0SS=99.43174271014956
ACCURACY_SCORE=0.92025
__2TIMES　of epoch__
L0SS=41.42596525869554
ACCURACY_SCORE=0.969
__3TIMES　of epoch__
L0SS=18.101265642743655
ACCURACY_SCORE=0.986

0.93
4min 23s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


### かなり時間　がかかる。